#robot_radius: 0.3
footprint: [[0.45,0.3], [0.45,-0.3], [-0.45, -0.3], [-0.45, 0.3]]
footprint_padding: 0.0

robot_base_frame: base_link

#layer definitions
static:
  map_topic: /map
  subscribe_to_updates: true

inflation_global:
  cost_scaling_factor: 3.0
  inflation_radius: 1.0

obstacles_ouster:
  track_unknown_space: true
  observation_sources: ouster_cloud
  expected_update_rate: 10,
  sensor_frame: base_link,
  combination_method: 1,
  observation_persistence: 0.1,
  ouster_cloud: {
    data_type: PointCloud2,
    clearing: true,
    marking: true,
    topic: /corrected_current_pcd,
    inf_is_valid: true,
    min_obstacle_height: 0.1,
    max_obstacle_height: 1.5,
    obstacle_range: 500.0,
    raytrace_range: 500.0
  }

inflation:
  cost_scaling_factor: 2.0
  inflation_radius: 0.5
