global_frame: odom
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5
static_map: true
track_unknown_space: true
resolution: 0.025
width: 10
height: 10

plugins:
  - { name: static,                  type: "costmap_2d::StaticLayer" }
  - { name: inflation_global,        type: "costmap_2d::InflationLayer" }
