base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

planner_frequency: 10
planner_patience: 3.0
planner_max_retries: 10

controller_frequency: 15.0
controller_patience: 3.0
controller_max_retries: 10

recovery_patience: 3.0
recovery_behaviour_enabled: true

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

conservative_reset:
  reset_distance: 1.0
  layer_names: [ 'obstacles_layer' ]
aggressive_reset:
  reset_distance: 1.0
  layer_names: [ 'inflation_layer' ]

oscillation_timeout: 2.5
oscillation_distance: 0.2
